// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/cerbos/query-plan-adapters/ent/example/ent/runtime.go

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
