package main

import (
	"bytes"
	"sort"

	"gopkg.in/yaml.v3"
)

const (
	resourceKind   = "conformance"
	generatedNotes = "Code generated by conformance/generator from conformance/cases/*.yaml. DO NOT EDIT."
)

// ruleKeyOrder puts a rule's well-known keys first so the policy reads like a hand-written one;
// anything else follows alphabetically.
var ruleKeyOrder = []string{"actions", "effect", "roles", "derivedRoles", "name", "condition", "output"}

// buildPolicy renders the single resource policy every case compiles into.
func buildPolicy(corpus *Corpus) ([]byte, error) {
	variables := map[string]string{}
	derived := map[string]bool{}
	for _, f := range corpus.Files {
		for k, v := range f.Variables {
			variables[k] = v
		}
		for _, name := range f.ImportDerivedRoles {
			derived[name] = true
		}
	}

	rp := mapping()
	add(rp, "version", scalar("default"))
	add(rp, "resource", scalar(resourceKind))
	if len(derived) > 0 {
		names := sortedKeys(derived)
		seq := &yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle}
		for _, n := range names {
			seq.Content = append(seq.Content, scalar(n))
		}
		add(rp, "importDerivedRoles", seq)
	}
	if len(variables) > 0 {
		local := mapping()
		for _, k := range sortedKeys(variables) {
			add(local, k, scalar(variables[k]))
		}
		vars := mapping()
		add(vars, "local", local)
		add(rp, "variables", vars)
	}

	rules := &yaml.Node{Kind: yaml.SequenceNode}
	for _, c := range corpus.Cases {
		for i, r := range c.rules() {
			rule := map[string]any{"actions": []any{c.ID}}
			for k, v := range r {
				rule[k] = v
			}
			node, err := orderedMapping(rule)
			if err != nil {
				return nil, err
			}
			if i == 0 {
				node.HeadComment = c.ID
			}
			rules.Content = append(rules.Content, node)
		}
	}
	add(rp, "rules", rules)

	root := mapping()
	root.HeadComment = generatedNotes
	add(root, "apiVersion", scalar("api.cerbos.dev/v1"))
	add(root, "resourcePolicy", rp)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func orderedMapping(m map[string]any) (*yaml.Node, error) {
	node := mapping()
	done := map[string]bool{}
	emit := func(k string) error {
		var v yaml.Node
		if err := v.Encode(m[k]); err != nil {
			return err
		}
		add(node, k, &v)
		done[k] = true
		return nil
	}
	for _, k := range ruleKeyOrder {
		if _, ok := m[k]; ok {
			if err := emit(k); err != nil {
				return nil, err
			}
		}
	}
	for _, k := range sortedKeys(m) {
		if !done[k] {
			if err := emit(k); err != nil {
				return nil, err
			}
		}
	}
	return node, nil
}

func mapping() *yaml.Node { return &yaml.Node{Kind: yaml.MappingNode} }

func scalar(s string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: s}
}

func add(m *yaml.Node, key string, value *yaml.Node) {
	m.Content = append(m.Content, scalar(key), value)
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
