name: Drizzle Test

on:
  pull_request:
    paths:
      - "drizzle/**"
      - "policies/**"
      - ".github/workflows/drizzle.yaml"
      - ".github/workflows/drizzle-publish.yaml"
  push:
    tags:
      - drizzle/v*

defaults:
  run:
    working-directory: drizzle

jobs:
  test:
    strategy:
      matrix:
        cerbos-version: ["latest"]
        node-version: ["20", "22", "24", "25"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Cerbos
        uses: cerbos/cerbos-setup-action@f772482c8504a05c49018a0bf2d84012a607733c # v1
        with:
          version: ${{ matrix.cerbos-version }}

      - name: Test using Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run test
