name: SQLAlchemy Publish

on:
  push:
    tags:
      - sqla/v*

defaults:
  run:
    working-directory: sqlalchemy

jobs:
  release-sqla:
    name: SQLA publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ./__pypackages__
          key: ${{ runner.os }}-python-${{ hashFiles('**/pdm.lock') }}

      - uses: pdm-project/setup-pdm@544d7237314ee09c256785bd360f6b30add38b37 # v4.6
        name: Setup PDM
        with:
          python-version: "3.10"  # Version range or exact version of a Python version to use, the same as actions/setup-python
          prerelease: true     # Allow prerelease versions to be installed
          enable-pep582: true  # Enable PEP 582 package loading globally

      - run: pdm install -G testcontainers

      - name: Set PDM version env
        run: echo "PDM_PEP517_SCM_VERSION=${GITHUB_REF_NAME#*\/}" >> $GITHUB_ENV

      - run: pdm build

      #- name: Publish to Test PyPI
        #uses: pypa/gh-action-pypi-publish@release/v1
        #with:
          #user: __token__
          #password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          #repository_url: https://test.pypi.org/legacy/
          #packages_dir: sqlalchemy/dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: sqlalchemy/dist/

      #- name: Create release
        #run: |-
          #gh release create "$GITHUB_REF_NAME" --generate-notes
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
