name: SQLAlchemy Publish

on:
  push:
    tags:
      - sqla/v*

defaults:
  run:
    working-directory: sqlalchemy

jobs:
  release-sqla:
    name: SQLA publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ./__pypackages__
          key: ${{ runner.os }}-python-${{ hashFiles('**/pdm.lock') }}

      - uses: pdm-project/setup-pdm@973541a5febeafcfdadf8a51211435be6ecfd90f # v4.5
        name: Setup PDM
        with:
          python-version: "3.10"  # Version range or exact version of a Python version to use, the same as actions/setup-python
          prerelease: true     # Allow prerelease versions to be installed
          enable-pep582: true  # Enable PEP 582 package loading globally

      - run: pdm install -G testcontainers

      - name: Set PDM version env
        run: echo "PDM_PEP517_SCM_VERSION=${GITHUB_REF_NAME#*\/}" >> $GITHUB_ENV

      - run: pdm build

      #- name: Publish to Test PyPI
        #uses: pypa/gh-action-pypi-publish@release/v1
        #with:
          #user: __token__
          #password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          #repository_url: https://test.pypi.org/legacy/
          #packages_dir: sqlalchemy/dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: sqlalchemy/dist/

      #- name: Create release
        #run: |-
          #gh release create "$GITHUB_REF_NAME" --generate-notes
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
